package com.hillspet.wearables.common.constants;

/**
 * @author vvodyaram This Class contains all the PROCEDURE and FUNCTION CALLS
 */
public interface SQLConstants {
	
	String HPN_AP_DATASET = System.getenv("HPN_AP_DATASET");

	String RESULT_SET_1 = "#result-set-1";
	String RESULT_SET_2 = "#result-set-2";
	String RESULT_SET_3 = "#result-set-3";
	String RESULT_SET_4 = "#result-set-4";
	String RESULT_SET_5 = "#result-set-5";
	String RESULT_SET_6 = "#result-set-6";
	String RESULT_SET_7 = "#result-set-7";

	/* device info related procedures */
	String DEVICE_INFO_INSERT = "DEVICE_INFO_INSERT";
	String DEVICE_INFO_UPDATE = "DEVICE_INFO_UPDATE";
	String DEVICE_INFO_DELETE = "DEVICE_INFO_DELETE";
	String DEVICE_INFO_UPDATE_DEVICE_FIRMWARE = "DEVICE_INFO_UPDATE_DEVICE_FIRMWARE";
	String GET_FIRMWARE_UPDATE_DETAILS_BY_DEVICE_IDS = "CALL GET_FIRMWARE_UPDATE_DETAILS_BY_DEVICE_IDS(?)";
	String DEVICE_INFO_GET_BY_ID = "CALL DEVICE_INFO_GET_BY_ID (?)";
	String DEVICE_INFO_GET_LIST = "CALL DEVICE_INFO_GET_LIST (?,?,?,?,?,?,?,?,?,?)";
	String ASSET_GET_LIST = "CALL ASSET_GET_LIST (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String DEVICE_INFO_GET_DEVICE_TYPES_AND_MODELS = "CALL DEVICE_INFO_GET_DEVICE_TYPES_AND_MODELS()";
	String DEVICE_INFO_GET_ALL_DEVICES = "CALL DEVICE_INFO_GET_ALL_DEVICES(?)";
	String ASSET_TYPE_LIST = "CALL ASSET_TYPE_GET_LIST()";
	String DEVICE_MODEL_LIST = "CALL DEVICE_MODEL_GET_LIST(?)";
	String DEVICE_GET_UNASSIGN_REASON_LIST = "CALL DEVICE_GET_UNASSIGN_REASON_LIST()";

	String DEVICE_INFO_LIST_COUNT = "select FN_GET_DEVICE_INFO_LIST_COUNT(?,?,?,?,?,?) as count";
	String ASSET_LIST_COUNT = "SELECT FN_GET_ASSET_LIST_COUNT(?,?,?,?,?,?,?,?,?,?,?) as count";

	String ASSET_DASHBOARD_GET_ASSETS_BY_ASSET_TYPE = "ASSET_DASHBOARD_GET_ASSETS_BY_ASSET_TYPE";
	String ASSET_DASHBOARD_GET_ASSETS_BY_STATUS = "CALL ASSET_DASHBOARD_GET_ASSETS_BY_STATUS(?,?,?)";
	
	String ASSET_GET_ASSET_BY_STUDY = "CALL ASSET_GET_ASSET_BY_STUDY(?,?,?,?,?,?,?,?,?,?)";
	String ASSET_GET_ASSET_BY_STUDY_COUNT = "SELECT FN_ASSET_GET_ASSET_BY_STUDY_COUNT(?,?,?,?,?,?,?,?,?,?) as count";

	
	String PET_GET_EXTERNAL_PET_INFO = "CALL PET_GET_EXTERNAL_PET_INFO(?,?)";

	/* firmware version related procedures */
	String FIRMWARE_VERSION_INSERT = "FIRMWARE_VERSION_INSERT";
	String FIRMWARE_VERSION_UPDATE = "FIRMWARE_VERSION_UPDATE";
	String FIRMWARE_VERSION_DELETE = "FIRMWARE_VERSION_DELETE";
	String FIRMWARE_VERSION_GET_BY_ID = "CALL FIRMWARE_VERSION_GET_BY_ID (?)";
	String FIRMWARE_VERSION_GET_LIST = "CALL FIRMWARE_VERSION_GET_LIST (?,?,?,?,?,?,?)";
	String FIRMWARE_VERSION_GET_ALL_VERSIONS = "CALL FIRMWARE_VERSION_GET_ALL_VERSIONS(?,?)";
	String FIRMWARE_VERSION_GET_ALL_VERSIONS_LIST = "CALL FIRMWARE_VERSION_GET_ALL_VERSIONS_LIST()";

	String GET_ASSET_UPDATE_HISTORY = "CALL GET_ASSET_UPDATE_HISTORY(?)";

	String FIRMWARE_VERSION_LIST_COUNT = "SELECT FN_GET_FIRMWARE_VERSION_LIST_COUNT(?,?,?) as count";

	String DEVICE_GET_UNCONGIFURED_DEVICE_LIST = "CALL DEVICE_GET_UNCONGIFURED_DEVICE_LIST()";

	/* users related procedures */
	String USER_INSERT = "USER_INSERT";
	String USER_UPDATE = "USER_UPDATE";
	String USER_UPDATE_PASSWORD = "USER_UPDATE_PASSWORD";
	String USER_DELETE = "USER_DELETE";
	String USER_GET_BY_ID = "USER_GET_BY_ID";
	String USER_GET_LIST = "CALL USER_GET_LIST (?,?,?,?,?,?,?)";
	String LOGIN_GET_USER_DETAILS_BY_USER_NAME = "LOGIN_GET_USER_DETAILS_BY_USER_NAME";
	String USER_GET_PASSWORD_HISTORY_BY_ID = "CALL USER_GET_PASSWORD_HISTORY_BY_ID(?)";
	String USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";

	String USER_LIST_COUNT = "SELECT FN_GET_USER_LIST_COUNT(?,?,?) as count";

	/* lookup data related procedures */
	String LU_GET_ROLE_TYPES = "CALL LU_GET_ROLE_TYPES()";
	String LU_GET_MENUS = "CALL LU_GET_MENUS(?)";
	String LU_GET_MENU_ACTIONS = "CALL LU_GET_MENU_ACTIONS()";
	String LU_GET_PET_BREEDS = "CALL LU_GET_PET_BREEDS()";
	String LU_GET_PET_STATUSES = "CALL LU_GET_PET_STATUSES()";
	String LU_GET_ROLES = "CALL LU_GET_ROLES()";
	String LU_GET_ACTIVE_ROLES = "CALL LU_GET_ACTIVE_ROLES()";
	String LU_GET_MOBILE_APP_CONFIGS = "CALL LU_GET_MOBILE_APP_CONFIGS()";
	String LU_GET_TICKET_TYPES = "CALL LU_GET_TICKET_TYPE()";
	String LU_GET_TICKEET_PRIORITIES = "CALL LU_GET_TICKET_PRIORITY()";
	String LU_GET_TICKET_STATUS = "CALL LU_GET_TICKET_STATUS()";
	String LU_GET_CUSTOMER_CONTACT_METHODS = "CALL LU_GET_CUSTOMER_CONTACT_METHOD()";
	String LU_GET_CUSTOMER_CONTACT_REASONS = "CALL LU_GET_CUSTOMER_CONTACT_REASON()";
	String LU_GET_TICKET_CATEGORIES = "CALL LU_GET_TICKET_CATEGORY()";
	String LU_GET_ISSUES = "CALL LU_GET_ISSUES()";
	String LU_GET_ROOT_CAUSE = "CALL LU_GET_ROOT_CAUSE(?)";
	String LU_GET_AGENT_ACTION = "CALL LU_GET_AGENT_ACTION(?)";
	String LU_GET_DEFENCIVE_SENSOR_ACTION = "CALL LU_GET_DEFENCIVE_SENSOR_ACTION()";
	String LU_GET_PET_NAME = "CALL LU_GET_PET_NAME(?)";
	String LU_GET_PET_PARENT_NAME = "CALL LU_GET_PET_PARENT_NAME(?)";
	String LU_GET_STUDY_NAME = "CALL LU_GET_STUDY_NAME(?,?,?)";
	String LU_GET_ACTIVE_STUDY = "CALL LU_GET_ACTIVE_STUDY(?,?)";
	String LU_GET_SENSOR_NAME = "CALL LU_GET_SENSOR_NAME(?,?,?)";
	String LU_GET_SENSOR_LOCATION = "CALL LU_GET_SENSOR_LOCATION()";
	String LU_GET_INVENTORY_STATUS = "CALL LU_GET_INVENTORY_STATUS(?)";
	String LU_GET_PRIORITY = "CALL LU_GET_PRIORITY()";
	String LU_GET_USERS = "CALL LU_GET_USERS()";
	String LU_GET_STATUS = "CALL LU_GET_STATUS()";
	String LU_GET_CONTACT_METHOD = "CALL LU_GET_CONTACT_METHOD()";
	String LU_GET_QUESTION_TYPES = "CALL LU_GET_QUESTION_TYPES()";
	String LU_GET_PRE_DEFINED_INSTRUCTIONS = "CALL LU_GET_PRE_DEFINED_INSTRUCTIONS()";
	String LU_GET_PRE_DEFINED_QUESTIONS = "LU_GET_PRE_DEFINED_QUESTIONS";
	String LU_GET_POINT_TRACKER_ACTIVITY = "CALL LU_GET_POINT_TRACKER_ACTIVITY()";
	String LU_GET_DEVICE_LOCATIONS = "CALL LU_GET_DEVICE_LOCATIONS()";
	String LU_GET_DEVICE_LOCATIONS_BULK_UPLOAD = "CALL LU_GET_DEVICE_LOCATIONS_BULK_UPLOAD()";
	String LU_GET_DEVICE_STATUSES = "CALL LU_GET_DEVICE_STATUSES(?)";
	String LU_GET_MOBILE_APP_FEEDBACK_PAGES = "CALL LU_GET_MOBILE_APP_FEEDBACK_PAGES()";
	String LU_GET_PET_BEHAVIORS_BY_SPECIES = "CALL LU_GET_PET_BEHAVIORS_BY_SPECIES(?, ?)";
	String LU_GET_PET_UNIQUE_BEHAVIORS = "CALL LU_GET_PET_UNIQUE_BEHAVIORS()";
	String LU_GET_POINT_TRACKER_METRICS = "CALL LU_GET_POINT_TRACKER_METRICS(?)";
	String LU_GET_POINT_TRACKER_METRICS_BY_ID = "CALL LU_GET_POINT_TRACKER_METRICS_BY_ID(?)";
	String LU_GET_RACKER_REJECT_REASONS = "CALL LU_GET_RACKER_REJECT_REASONS()";
	String LU_GET_DEVICE_TYPE = "CALL LU_GET_DEVICE_TYPE()";
	String LU_GET_DEVICE_MODEL = "CALL LU_GET_DEVICE_MODEL(?)";
	String LU_GET_ALL_STUDY_NAME = "CALL LU_GET_ALL_STUDY_NAME()";
	String LU_GET_ACTIVE_STUDY_NAME = "CALL LU_GET_ACTIVE_STUDY_NAME()";
	String LU_GET_SPECIES = "CALL LU_GET_SPECIES()";
	String LU_GET_USERS_ASSIGNED_TO_TICKET = "CALL LU_GET_USERS_ASSIGNED_TO_TICKET()";
	String LU_GET_PET_PARENT_NAME_TIMER = "CALL LU_GET_PET_PARENT_NAME_TIMER()";
	String LU_GET_PET_NAME_TIMER = "CALL LU_GET_PET_NAME_TIMER()";
	String LU_GET_CATEGORY_TIMER = "CALL LU_GET_CATEGORY_TIMER()";
	String LU_GET_PRELUDE_STUDY = "CALL LU_GET_PRELUDE_STUDY()";
	String LU_GET_EXTRENAL_FILE_CATEGORY = "CALL LU_GET_EXTRENAL_FILE_CATEGORY(?)";
	String LU_GET_ALL_CAMPAIGNS = "CALL LU_GET_ALL_CAMPAIGNS()";
	String LU_GET_QUESTIONNIRE_OCCURANCES = "CALL LU_GET_QUESTIONNIRE_OCCURANCES(?)";
	String LU_GET_QUESTIONNIRE_FREQUENCIES = "CALL LU_GET_QUESTIONNIRE_FREQUENCIES(?)";
	String LU_GET_MATERIAL_TYPE = "CALL LU_GET_MATERIAL_TYPE()";
	String LU_GET_MATERIAL_CATEGORY = "CALL LU_GET_MATERIAL_CATEGORY()";
	String LU_GET_ENTHUSIASM_SCALES = "CALL LU_GET_ENTHUSIASM_SCALES(?)";
	String LU_GET_PET_FEEDING_TIMES = "CALL LU_GET_PET_FEEDING_TIMES()";
	String LU_GET_IMAGE_SCORING_TYPES = "CALL LU_GET_IMAGE_SCORING_TYPES()";
	String LU_GET_SHIPMENT_COMPANIES = "CALL LU_GET_SHIPMENT_COMPANIES()";
	String LU_GET_QUESTIONNAIRE_TYPES = "CALL LU_GET_QUESTIONNAIRE_TYPE(?)";
	String LU_GET_QUESTIONNAIRE_CATEGORY = "CALL LU_GET_QUESTIONNAIRE_CATEGORY(?)";
	String LU_GET_TIMEZONE_BY_NAME = "CALL LU_GET_TIMEZONE_BY_NAME(?)";
	String LU_GET_ALGORITHMS = "CALL LU_GET_ALGORITHMS()";
	String LU_GET_QUESTION_CATEGORY = "CALL LU_GET_QUESTION_CATEGORY()";
	String LU_GET_QUESTION_VALIDITY_PERIODS = "CALL LU_GET_QUESTION_VALIDITY_PERIODS()";
	String LU_GET_COUNTRIES = "CALL LU_GET_COUNTRIES()";
	String LU_GET_BFI_SCORER_LIST = "CALL LU_GET_BFI_SCORER_LIST()";
	String LU_GET_MEASUREMENT_UNITS = "CALL LU_GET_MEASUREMENT_UNITS(?)";
	String LU_GET_STUDY_PHASES = "CALL LU_GET_STUDY_PHASES()";
	String LU_GET_STUDY_STATUS = "CALL LU_GET_STUDY_STATUS()";
	String LU_GET_PRODUCT_TYPES = "CALL LU_GET_PRODUCT_TYPES()";
	String LU_GET_STUDY_LOCATION_LIST = "CALL LU_GET_STUDY_LOCATION_LIST()";
	String LU_GET_STUDY_PHASE_DURATION_UNITS = "CALL LU_GET_STUDY_PHASE_DURATION_UNITS()";
	String LU_GET_DIETS = "CALL LU_GET_DIETS()";
	String LU_GET_PET_NAME_BY_STUDY = "CALL LU_GET_PET_NAME_BY_STUDY(?)";
	String LU_GET_FREQUENCIES = "CALL LU_GET_FREQUENCIES(?)";
	String LU_GET_QUESTIONNAIRE_BY_STUDY_PHASE = "CALL LU_GET_QUESTIONNAIRE_BY_STUDY_PHASE(?,?,?,?)";
	String LU_GET_WIFI_SSID = "CALL LU_GET_WIFI_SSID";
	String LU_GET_BEHAVIOR_TYPES = "CALL LU_GET_BEHAVIOR_TYPES()";

	/* Role related procedures */
	String ROLE_INSERT = "ROLE_INSERT";
	String ROLE_UPDATE = "ROLE_UPDATE";
	String ROLE_DELETE = "ROLE_DELETE";
	String ROLE_GET_BY_ID = "CALL ROLE_GET_BY_ID(?)";
	String ROLE_GET_LIST = "CALL ROLE_GET_LIST (?,?,?,?,?,?,?)";

	String ROLE_LIST_COUNT = "SELECT FN_GET_ROLE_LIST_COUNT(?,?,?) as count";

	/* Mobile App Feedback related procedures & Functions */
	String MOBILE_APP_FEEDBACK_COUNT = "SELECT FN_GET_MOBILE_APP_FEEDBACK_COUNT(?,?,?,?,?,?,?) as count";	
	String MOBILE_APP_FEEDBACK_LIST = "CALL MOBILE_APP_FEEDBACK_LIST (?,?,?,?,?,?,?,?,?,?,?,?)";
	String MOBILE_APP_SELF_ONBOARD_COUNT = "SELECT FN_GET_MOBILE_APP_SELF_ONBOARD_COUNT(?,?,?,?,?) as count";
	String MOBILE_APP_SELF_ONBOARDING_LIST = "CALL MOBILE_APP_SELF_ONBOARD_GET_LIST (?,?,?,?,?,?,?,?,?)";
	String PET_ASSIGN_STUDY = "PET_ASSIGN_STUDY";

	/* AuditLog related Procedures */
	String AUDIT_LOG_INSERT = "AUDIT_LOG_INSERT";
	String AUDIT_LOG_WITH_REQUEST_FROM_INSERT = "AUDIT_LOG_WITH_REQUEST_FROM_INSERT";
	String AUDIT_LOG_GET_LIST = "CALL AUDIT_LOG_GET_LIST(?,?,?,?,?,?,?,?,?,?,?)";
	String AUDIT_LOG_GET_ACTIVITY = "CALL AUDIT_LOG_GET_ACTIVITY(?,?)";
	String AUDIT_LOG_COUNT = "SELECT FN_GET_AUDIT_LOG_COUNT(?,?,?,?,?,?,?) as count";

	/* Study related procedures & Functions */
	String STUDY_NOTIFICATION_GET_LIST_COUNT = "SELECT FN_GET_STUDY_NOTIFICATION_LIST_COUNT(?, ?, ?,?) as count";
	String STUDY_NOTIFICATION_GET_LIST = "CALL STUDY_NOTIFICATION_GET_LIST(?, ?, ?, ?, ?, ?, ?,?)";
	String STUDY_GET_BASIC_DETAILS_BY_ID = "STUDY_GET_BASIC_DETAILS_BY_ID";
	String STUDY_DIET_INSERT = "STUDY_DIET_INSERT";
	String STUDY_DIET_GET_LIST_COUNT = "SELECT FN_GET_STUDY_DIET_LIST_COUNT(?,?) as count";
	String STUDY_DIET_GET_LIST = "CALL STUDY_DIET_GET_LIST(?,?,?,?,?,?)";
	String STUDY_DIET_VALIDATE_FOR_DELETE = "STUDY_DIET_VALIDATE_FOR_DELETE";
	String STUDY_PLAN_INSERT = "STUDY_PLAN_INSERT";
	String STUDY_PLAN_GET_LIST = "CALL STUDY_PLAN_GET_LIST(?)";
	String STUDY_MOBILE_APP_CONFIG_INSERT = "STUDY_MOBILE_APP_CONFIG_INSERT";
	String STUDY_MOBILE_APP_CONFIG_GET_LIST = "CALL STUDY_MOBILE_APP_CONFIG_GET_LIST(?)";
	String STUDY_NOTES_INSERT = "STUDY_NOTES_INSERT";
	String STUDY_NOTES_GET_LIST = "CALL STUDY_NOTES_GET_LIST(?, ?)";
	String STUDY_PRELUDE_CONFIG_INSERT = "STUDY_PRELUDE_CONFIG_INSERT";
	String STUDY_PRELUDE_CONFIG_GET_LIST = "STUDY_PRELUDE_CONFIG_GET_LIST";
	String STUDY_ACTIVITY_FACTOR_CONFIG_INSERT = "STUDY_ACTIVITY_FACTOR_CONFIG_INSERT";
	String STUDY_ACTIVITY_FACTOR_CONFIG_GET_LIST = "CALL STUDY_ACTIVITY_FACTOR_CONFIG_GET_LIST(?)";

	String STUDY_NOTIFICATION_UPDATE_STATUS = "STUDY_NOTIFICATION_STATUS_UPDATE";
	String STUDY_GET_LIST_COUNT = "SELECT FN_GET_STUDY_LIST_COUNT(?,?,?,?,?) as count";
	String STUDY_GET_LIST = "CALL STUDY_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String STUDY_GET_ALL_STUDY_LIST = "CALL STUDY_GET_ALL_STUDY_LIST(?,?,?)";
	String STUDY_GET_ALL_STUDY_LIST_BY_USER = "CALL STUDY_GET_ALL_STUDY_LIST_BY_USER(?)";
	String STUDY_GET_ALL_STUDY_LIST_ACTIVE_INACTIVE = "CALL STUDY_GET_ALL_STUDY_LIST_ACTIVE_INACTIVE()";
	String STUDY_GET_STUDY_LIST_BY_PET_PARENT_AND_PET = "CALL STUDY_GET_STUDY_LIST_BY_PET_PARENT_AND_PET(?,?)";
	String STUDY_INSERT = "STUDY_INSERT";
	String STUDY_INSERT_NEW = "STUDY_INSERT_NEW";
	String STUDY_INSERT_CROSS_OVER = "STUDY_INSERT_CROSS_OVER";
	String STUDY_GET_BY_ID = "STUDY_GET_BY_ID";
	String STUDY_GET_ASSOCIATED_PETS = "CALL STUDY_GET_ASSOCIATED_PETS(?)";
	String STUDY_DISASSOCIATE_PLAN = "STUDY_DISASSOCIATE_PLAN";
	String STUDY_ASSOCIATE_PLAN = "STUDY_ASSOCIATE_PLAN";
	String STUDY_UPDATE = "STUDY_UPDATE";
	String STUDY_UPDATE_NEW = "STUDY_UPDATE_NEW";
	String STUDY_DELETE = "STUDY_DELETE";
	String STUDY_DISASSOCIATE_QUESTIONNAIRE = "STUDY_DISASSOCIATE_QUESTIONNAIRE";
	String STUDY_ASSOCIATE_QUESTIONNAIRE = "STUDY_ASSOCIATE_QUESTIONNAIRE";
	String STUDY_UPDATE_QUESTIONNAIRE = "STUDY_UPDATE_QUESTIONNAIRE";
	String STUDY_GET_ASSOCIATED_QUESTIONNAIRES = "CALL STUDY_GET_ASSOCIATED_QUESTIONNAIRES(?)";
	String GET_ALL_PRELUDE_DATA = "CALL GET_ALL_PRELUDE_DATA(?)";
	String GET_PRELUDE_DATA_BY_STUDY = "CALL GET_PRELUDE_DATA_BY_STUDY(?)";
	String GET_ALL_AF_PRELUDE_DATA = "CALL GET_ALL_AF_PRELUDE_DATA(?)";
	String GET_AF_PRELUDE_DATA_BY_STUDY = "CALL GET_AF_PRELUDE_DATA_BY_STUDY(?)";
	String STUDY_ID_GET_BY_NAME = "CALL STUDY_ID_GET_BY_NAME(?)";

	String STUDY_PHASE_PET_INSERT = "STUDY_PHASE_PET_INSERT";
	String STUDY_PHASE_PET_REMOVE = "STUDY_PHASE_PET_REMOVE";
	String GET_STUDY_PHASE_PET_LIST_COUNT = "SELECT FN_GET_STUDY_PHASE_PET_LIST_COUNT(?,?,?,?,?,?,?,?,?,?) as count";
	String STUDY_PHASE_GET_PET_LIST = "CALL STUDY_PHASE_GET_PET_LIST(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

	String STUDY_DIARY_GET_LIST_COUNT = "SELECT FN_GET_STUDY_DIARY_LIST_COUNT(?,?,?,?) as count";
	String STUDY_DIARY_GET_LIST = "CALL STUDY_DIARY_GET_LIST(?,?,?,?,?,?,?,?)";
	String STUDY_FEEDING_SCHEDULE_GET_LIST_COUNT = "SELECT FN_GET_STUDY_FEEDING_SCHEDULE_COUNT(?,?,?,?,?,?,?,?) as count";
	String STUDY_FEEDING_SCHEDULE_GET_LIST = "CALL STUDY_FEEDING_SCHEDULE_GET_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";
	String STUDY_FEEDING_SCHEDULE_DELETE = "STUDY_FEEDING_SCHEDULE_DELETE";
	String STUDY_EXTEND_PHASE = "STUDY_EXTEND_PHASE";

	/* Plan related procedures & Functions */
	String PLAN_GET_LIST_COUNT = "SELECT FN_GET_PLAN_LIST_COUNT(?,?,?,?,?) as count";
	String PLAN_GET_LIST = "CALL PLAN_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String PLANS_INSERT = "PLAN_INSERT";
	String PLAN_DETAILS_VIEW = "CALL PLAN_DETAILS_VIEW(?)";
	String PLAN_GET_PLANS = "CALL PLAN_GET_PLANS(?,?)";
	String PLAN_GET_BY_ID = "PLAN_GET_BY_ID";
	String PLAN_UPDATE = "PLAN_UPDATE";
	String PLAN_DELETE = "PLAN_DELETE";

	/* Pet related procedures & Functions */
	String PET_INSERT = "PET_INSERT";
	String PET_UPDATE = "PET_UPDATE";
	String PET_GET_BY_ID = "PET_GET_BY_ID";
	String PET_GET_BY_ID_AND_STUDY_ID = "CALL PET_GET_BY_ID_AND_STUDY_ID(?,?)";
	String PET_DELETE = "PET_DELETE";
	String PET_GET_ALL_PETS = "CALL PET_GET_ALL_PETS(?)";
	String PET_GET_VIEW_PANE_COUNT = "SELECT FN_GET_PET_VIEW_PANE_COUNT(?,?,?) as count";
	String PET_GET_VIEW_PANE = "CALL PET_GET_VIEW_PANE(?,?,?,?,?)";
	String PET_GET_LIST = "CALL PET_GET_LIST(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_GET_PET_OBSERVATIONS_COUNT = "SELECT FN_GET_PET_OBSERVATIONS_COUNT(?,?,?,?,?,?,?,?) as count";
	String PET_GET_OBSERVATIONS_BY_PET_AND_STUDY_ID = "CALL PET_GET_OBSERVATIONS_BY_PET_AND_STUDY_ID(?,?,?,?,?,?,?,?,?,?,?,?)";
	String PET_GET_PARENTS_BY_PET = "CALL PET_GET_PARENTS_BY_PET(?,?,?,?,?)";
	String PET_GET_NOTES_BY_PET = "CALL PET_GET_NOTES_BY_PET(?,?,?,?,?)";
	String PET_GET_DEVICES_BY_PET = "CALL PET_GET_DEVICES_BY_PET(?)";
	String PET_NOTES_INSERT = "PET_NOTES_INSERT";
	String PET_GET_LIST_BY_PET_PARENT = "CALL PET_GET_LIST_BY_PET_PARENT(?)";
	String PET_GET_LIST_COUNT = "SELECT FN_GET_PET_LIST_COUNT(?,?,?,?,?,?,?,?,?) as count";
	String PET_ASSOCIATE_NEW_STUDY = "PET_ASSOCIATE_NEW_STUDY";
	String PET_ADD_WEIGHT = "PET_ADD_WEIGHT";
	String PET_UPDATE_WEIGHT = "PET_UPDATE_WEIGHT";
	String PET_FEEDING_ENTHUSIASM_SCALE_GET_LIST = "CALL PET_FEEDING_ENTHUSIASM_SCALE_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String PET_FEEDING_ENTHUSIASM_SCALE_GET_COUNT = "SELECT FN_GET_PET_FEEDING_ENTHUSIASM_SCALE_COUNT(?,?,?,?,?,?) AS COUNT";
	String PET_GET_ADDRESSES_BY_ID = "CALL PET_GET_ADDRESSES_BY_ID(?)";
	String PET_GET_DEVICE_HISTORY_BY_STREAM_ID = "CALL PET_GET_DEVICE_HISTORY_BY_STREAM_ID(?,?)";

	String PET_IMAGE_SCALE_GET_LIST = "CALL PET_IMAGE_SCALE_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String PET_IMAGE_SCALE_GET_COUNT = "SELECT FN_GET_PET_IMAGE_SCALE_GET_COUNT(?,?,?,?,?,?) AS COUNT";
	String PET_GET_PARENTS_LIST_COUNT = "SELECT FN_PET_GET_PARENTS_LIST_COUNT(?) AS COUNT";
	String PET_GET_NOTES_LIST_COUNT = "SELECT FN_PET_GET_NOTES_LIST_COUNT(?) AS COUNT";
	String PET_GET_DEVICES_LIST_COUNT = "SELECT FN_PET_GET_DEVICES_LIST_COUNT(?,?) AS COUNT";

	String PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET_COUNT = "SELECT FN_PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET_COUNT(?,?,?,?) AS COUNT";
	String PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET = "CALL PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET(?,?,?,?,?,?,?,?,?)";

	String PET_DISASSOCIATE_STUDY = "PET_DISASSOCIATE_STUDY";
	String PET_GET_WEIGHT_HISTORY = "PET_GET_WEIGHT_HISTORY_LIST";
	String PET_GET_WEIGHT_HISTORY_COUNT = "SELECT FN_GET_PET_WEIGHT_HISTORY_COUNT(?,?,?) as count";
	String PET_GET_CURRENT_STUDY_LIST = "CALL PET_GET_CURRENT_STUDY_LIST(?,?)";
	String PET_GET_ARCHIVE_STUDY_LIST = "CALL PET_GET_ARCHIVE_STUDY_LIST(?,?)";
	String PET_GET_DEVICES_BY_PET_ID_AND_STUDY_ID = "CALL PET_GET_DEVICES_BY_PET_ID_AND_STUDY_ID(?,?,?,?,?,?)";
	String PET_GET_DETAILS_BY_ID = "PET_GET_DETAILS_BY_ID";
	String PET_GET_ALL_CAMPAIGN_POINTS_BY_PET = "CALL PET_GET_ALL_CAMPAIGN_POINTS_BY_PET(?)";
	String PET_GET_LEG_LENGTH_HISTORY_BY_ID = "CALL PET_GET_LEG_LENGTH_HISTORY_BY_ID(?,?)";
	String PET_EXTERNAL_IDS_BULK_SAVE = "PET_EXTERNAL_IDS_BULK_SAVE";
	String PET_EXT_IDS_BULK_STAGING_LIST_COUNT = "SELECT FN_GET_PET_EXT_IDS_BULK_STAGING_LIST_COUNT(?) as count";
	String PET_EXT_IDS_BULK_STAGING_LIST = "CALL PET_EXT_IDS_BULK_STAGING_LIST (?,?,?)";
	String PET_SAVE_BULK_EXTPETS_STAGING = "PET_SAVE_BULK_EXTPETS_STAGING";

	// FOR VIEW PET CAMPAIGN POINTS LIST
	String PET_GET_CAMPAIGN_POINTS_LIST_COUNT_BY_PET = "SELECT FN_GET_PET_CAMPAIGN_POINTS_LIST_COUNT_BY_PET(?,?) AS COUNT";
	String PET_GET_CAMPAIGN_POINTS_LIST_BY_PET = "CALL PET_GET_CAMPAIGN_POINTS_LIST(?,?,?,?,?,?)";
	String PET_GET_REWARD_POINTS_LIST_COUNT_BY_PET = "SELECT FN_GET_PET_REWARD_POINTS_LIST_COUNT_BY_PET(?) as count";
	String PET_GET_REDEEMTION_HISTORY_BY_PET = "CALL PET_GET_REDEEMTION_HISTORY_BY_PET(?)";

	String PET_REDEEM_POINTS = "PET_REDEEM_POINTS";
	String PET_GET_EXTERNAL_INFO_LIST = "call PET_GET_EXTERNAL_INFO_LIST(?)";
	String PET_UPDATE_IBW = "PET_UPDATE_IBW";
	
	String PET_GET_ACTIVE_PET_LIST_COUNT = "SELECT FN_PET_GET_ACTIVE_PET_LIST_COUNT(?,?,?,?,?,?,?,?,?,?,?) as count";
	String PET_GET_ACTIVE_PET_LIST = "CALL PET_GET_ACTIVE_PET_LIST(?,?,?,?,?,?,?,?,?,?,?)";

	/* Pet Parent related procedures & Functions */
	String PET_PARENT_INSERT = "PET_PARENT_INSERT";
	String PET_PARENT_UPDATE = "PET_PARENT_UPDATE";
	String PET_PARENT_GET_BY_ID = "PET_PARENT_GET_BY_ID";
	String PET_PARENT_GET_ALL = "CALL PET_PARENT_GET_ALL(?)";
	String PET_PARENT_GET_LIST_COUNT = "select FN_GET_PET_PARENT_LIST_COUNT(?,?,?,?,?) as count";
	String PET_PARENT_GET_LIST = "CALL PET_PARENT_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String PET_PARENT_DELETE = "PET_PARENT_DELETE";
	String PET_PARENT_VALIDATE_EMAIL = "PET_PARENT_VALIDATE_EMAIL";
	String PET_PARENT_GET_ADDRESSES_BY_ID = "PET_PARENT_GET_ADDRESSES_BY_ID";
	String PET_PARENT_VALIDATE_ADDRESS_UNASSIGNED_PET = "PET_PARENT_VALIDATE_ADDRESS_UNASSIGNED_PET";

	/* point tracker related procedures */
	String POINT_TRACKER_INSERT = "POINT_TRACKER_INSERT";
	String POINT_TRACKER_GET_LIST_COUNT = "SELECT FN_GET_POINT_TRACKER_LIST_COUNT(?,?,?,?,?,?,?) as count";
	String POINT_TRACKER_GET_LIST = "CALL POINT_TRACKER_LIST(?,?,?,?,?,?,?,?,?,?,?)";
	String POINT_TRACKER_UPDATE = "POINT_TRACKER_UPDATE";
	String POINT_TRACKER_GET_BY_ID = "POINT_TRACKER_GET_BY_ID";
	String POINT_TRACKER_ACTIVITIES_GET_LIST_COUNT = "select FN_GET_POINT_TRACKER_ACTIVITY_LIST_COUNT(?,?,?,?,?,?,?,?) as count";
	String POINT_TRACKER_ACTIVITIES_GET_LIST = "CALL POINT_TRACKER_ACTIVITY_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";
	String TRACKER_STATUS_UPDATE = "POINT_TRACKER_ACTIVITY_STATUS_UPDATE";
	String FN_GET_POINT_TRACKER_REPORT_COUNT = "SELECT FN_GET_POINT_TRACKER_REPORT_COUNT(?,?,?,?,?,?) as count";
	String FN_GET_POINTS_ACCUMULATED_REPORT_COUNT = "SELECT FN_GET_POINTS_ACCUMULATED_REPORT_COUNT(?,?,?,?,?,?) as count";
	String GET_POINT_TRACKER_REPORT = "CALL GET_POINT_TRACKER_REPORT(?,?,?,?,?,?,?,?,?,?)";
	String GET_POINTS_ACCUMULATED_REPORT = "CALL GET_POINTS_ACCUMULATED_REPORT(?,?,?,?,?,?,?,?,?,?)";

	/* Support related Procedures & Functions */
	String CUSTOMER_SUPPORT_INSERT = "CUSTOMER_SUPPORT_INSERT";
	String CUSTOMER_SUPPORT_UPDATE = "CUSTOMER_SUPPORT_UPDATE";
	String CUSTOMER_SUPPORT_GET_BY_ID = "CUSTOMER_SUPPORT_GET_BY_ID";
	String CUSTOMER_SUPPORT_DETAILS_GET_BY_ID = "CUSTOMER_SUPPORT_DETAILS_GET_BY_ID";
	String CUSTOMER_SUPPORT_HISTORY_GET_BY_ID = "CUSTOMER_SUPPORT_HISTORY_GET_BY_ID";
	String CUSTOMER_SUPPORT_INSERT_FILE_NAME = "CUSTOMER_SUPPORT_INSERT_FILE_NAME";
	String CUSTOMER_SUPPORT_GET_LIST = "CALL CUSTOMER_SUPPORT_GET_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";
	String CUSTOMER_SUPPORT_GET_LIST_COUNT = "SELECT FN_GET_CUSTOMER_SUPPORT_COUNT(?,?,?,?,?,?,?,?) as count";
	String CUSTOMER_SUPPORT_GET_UPLOADED_FILE = "CALL CUSTOMER_SUPPORT_GET_UPLOADED_FILE(?,?)";
	String CUSTOMER_SUPPORT_GET_LIST_REPORT_COUNT = "SELECT FN_GET_CUSTOMER_SUPPORT_REPORT_COUNT(?,?,?,?,?,?,?) as count";
	String CUSTOMER_SUPPORT_GET_LIST_REPORT = "CALL CUSTOMER_SUPPORT_GET_LIST_REPORT(?,?,?,?,?,?,?,?,?,?,?)";
	String ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE = "CALL ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE(?,?,?,?,?)";
	String ASSET_DASHBOARD_GET_ASSETS_BY_TICKETS_STUDY = "CALL ASSET_DASHBOARD_GET_ASSETS_BY_TICKETS_STUDY(?,?,?)";
	String FILE_DELETE = "FILE_DELETE";
	String CUSTOMER_SUPPORT_GET_NOW = "SELECT NOW() NOW";

	/* Support Material related procedures & functions */
	String SUPPORT_MATERIAL_INSERT = "SUPPORT_MATERIAL_INSERT";
	String SUPPORT_MATERIAL_GET_LIST_COUNT = "SELECT FN_GET_SUPPORT_MATERIAL_GET_LIST_COUNT(?) as count";
	String SUPPORT_MATERIAL_GET_LIST = "CALL SUPPORT_MATERIAL_GET_LIST(?,?,?,?,?)";
	String SUPPORT_MATERIAL_DETAILS_GET_LIST = "CALL SUPPORT_MATERIAL_DETAILS_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String SUPPORT_MATERIAL_DETAILS_LIST_COUNT = "SELECT FN_GET_SUPPORT_MATERIAL_DETAILS_LIST_COUNT(?,?,?,?,?) as count";
	String SUPPORT_MATERIAL_DETAILS_BY_ID = "SUPPORT_MATERIAL_DETAILS_BY_ID";
	String SUPPORT_MATERIAL_UPDATE = "SUPPORT_MATERIAL_UPDATE";
	String SUPPORT_MATERIAL_VALIDATE_TITLE = "SUPPORT_MATERIAL_VALIDATE_TITLE";
	String SUPPORT_MATERIAL_DELETE = "SUPPORT_MATERIAL_DELETE";

	/* User Favorites related procedures & Functions */
	String USER_FAVOURITE_INSERT = "USER_FAVOURITE_INSERT";
	String USER_FAVOURITE_UPDATE = "USER_FAVOURITE_UPDATE";
	String USER_FAVOURITES_LIST_COUNT = "SELECT FN_GET_USER_FAVOURITES_LIST_COUNT(?,?,?,?,?) as count";
	String USER_FAVOURITE_GET_LIST = "CALL USER_FAVOURITE_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String IS_USER_FAVOURITES = "SELECT FN_GET_IS_USER_FAVOURITES(?,?,?,?) as isFavourite";
	String FN_GET_USER_VALIDATE_ASSOCIATED_STUDY = "SELECT FN_GET_USER_VALIDATE_ASSOCIATED_STUDY(?,?,?) as isStudyExist";

	/* Questionnaires related procedures & Functions */
	String QUESTION_CATEGORY_INSERT = "QUESTION_CATEGORY_INSERT";
	String QUESTION_CATEGORY_UPDATE = "QUESTION_CATEGORY_UPDATE";
	String QUESTION_CATEGORY_DELETE = "QUESTION_CATEGORY_DELETE";
	String QUESTION_CATEGORY_GET_BY_ID = "CALL QUESTION_CATEGORY_GET_BY_ID(?)";
	String QUESTION_CATEGORY_GET_LIST_COUNT = "SELECT FN_GET_QUESTION_CATEGORY_COUNT(?,?) as count";
	String QUESTION_CATEGORY_GET_LIST = "CALL QUESTION_CATEGORY_GET_LIST(?,?,?,?,?,?)";
	String QUESTION_CATEGORY_GET_ALL_LIST = "CALL QUESTION_CATEGORY_GET_ALL_LIST()";

	String QUESTIONNAIRE_INSERT = "QUESTIONNAIRE_INSERT";
	String QUESTIONNAIRE_UPDATE = "QUESTIONNAIRE_UPDATE";
	String QUESTIONNAIRE_GET_BY_ID = "QUESTIONNAIRE_GET_BY_ID";
	String QUESTIONNAIRE_GET_LIST_COUNT = "SELECT FN_GET_QUESTIONNAIRE_COUNT(?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_GET_LIST = "CALL QUESTIONNAIRE_GET_LIST(?,?,?,?,?,?,?,?,?,?)";	
	String QUESTIONNAIRE_GET_LIST_FOR_EXPORT = "CALL QUESTIONNAIRE_GET_LIST_FOR_EXPORT(?,?,?,?,?,?,?,?,?,?)";	
	String QUESTIONNAIRE_GET_ALL_LIST = "CALL QUESTIONNAIRE_GET_ALL_LIST(?)";
	String QUESTIONNAIRE_GET_BY_PET = "CALL QUESTIONNAIRE_GET_BY_PET(?)";
	String QUESTIONNAIRE_DELETE = "QUESTIONNAIRE_DELETE";
	String QUESTIONNAIRE_INSERT_INSTRUCTION = "QUESTIONNAIRE_INSTRUCTION_INSERT";
	String QUESTIONNAIRE_DELETE_INSTRUCTION = "QUESTIONNAIRE_INSTRUCTION_DELETE";
	String QUESTIONNAIRE_UPDATE_INSTRUCTION = "QUESTIONNAIRE_INSTRUCTION_UPDATE";
	String QUESTIONNAIRE_INSERT_QUESTION = "QUESTIONNAIRE_QUESTION_INSERT";
	String QUESTIONNAIRE_DELETE_QUESTION = "QUESTIONNAIRE_QUESTION_DELETE";
	String QUESTIONNAIRE_UPDATE_QUESTION = "QUESTIONNAIRE_QUESTION_UPDATE";
	String QUESTIONNAIRE_GET_ACTIVE_QUESTIONNAIRES = "CALL QUESTIONNAIRE_GET_ACTIVE_QUESTIONNAIRES(?)";
	String QUESTIONNAIRE_RESPONSE_GET_LIST = "CALL QUESTIONNAIRE_RESPONSE_GET_LIST(?,?,?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY = "CALL QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_RESPONSE_GET_LIST_COUNT = "SELECT FN_GET_QUESTIONNAIRE_RESPONSE_LIST_COUNT(?,?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY_COUNT = "SELECT FN_QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY_COUNT(?,?,?,?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_RESPONSE_BY_PET_COUNT = "SELECT FN_GET_QUESTIONNAIRE_RESPONSE_BY_PET_COUNT(?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_RESPONSE_LIST_BY_PET = "CALL QUESTIONNAIRE_RESPONSE_LIST_BY_PET(?,?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_VIEW_RESPONSE_DETAILS = "CALL QUESTIONNAIRE_VIEW_RESPONSE_DETAILS(?,?)";
	String QUESTIONNAIRE_VIEW_RESPONSE = "CALL QUESTIONNAIRE_VIEW_RESPONSE(?)";
	String QUESTIONNAIRE_SKIP_UPDATE = "QUESTIONNAIRE_SKIP_UPDATE";
	String QUESTIONNAIRE_UPDATE_REPUBLISH = "QUESTIONNAIRE_UPDATE_REPUBLISH";
	String QUESTIONNAIRE_GET_PUBLISH_HISTORY = "CALL QUESTIONNAIRE_GET_PUBLISH_HISTORY(?)";
	String FN_GET_PROPOSED_QUESTIONNAIRE_NAME = "select FN_GET_COPY_QUESTIONNAIRE_NAME(?) as proposedQuestionnaireName";

	String STUDY_QUESTIONNAIRE_DATA_EXTRACT_CONFIG_GET_BY_ID = "STUDY_QUESTIONNAIRE_DATA_EXTRACT_CONFIG_GET_BY_ID";
	String STUDY_QUESTIONNAIRE_DATA_EXTRACT_CONFIG_INSERT = "STUDY_QUESTIONNAIRE_DATA_EXTRACT_CONFIG_INSERT";

	/* Device related procedures & Functions */
	String GET_DEVICE_DETAILS_REPORT = "call GET_DEVICE_DETAILS_REPORT(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_DETAILS_REPORT_COUNT = "select FN_GET_DEVICE_DETAILS_REPORT_COUNT(?,?,?,?,?,?,?,?,?) as count";	

	String GET_DEVICE_MALFUNCTION_REPORT = "CALL GET_DEVICE_MALFUNCTION_REPORT(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_MALFUNCTION_REPORT_COUNT = "SELECT FN_GET_DEVICE_MALFUNCTION_REPORT_COUNT(?,?,?,?,?,?,?,?,?) as count";

	String GET_DEVICE_HISTORY_REPORT = "CALL GET_DEVICE_HISTORY_REPORT(?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_HISTORY_REPORT_COUNT = "SELECT FN_GET_DEVICE_HISTORY_REPORT_COUNT(?,?,?,?,?,?,?,?) as count";

	String FN_GET_DEVICE_INVENTORY_REPORT_COUNT = "select FN_GET_DEVICE_INVENTORY_REPORT_COUNT(?,?,?,?) as count";
	String GET_DEVICE_INVENTORY_REPORT = "call GET_DEVICE_INVENTORY_REPORT(?,?,?,?,?,?,?,?)";

	String FN_GET_DEVICE_TRACKING_REPORT_COUNT = "SELECT FN_GET_DEVICE_TRACKING_REPORT_COUNT(?,?,?,?,?,?,?,?) as count";
	String GET_DEVICE_TRACKING_REPORT = "CALL GET_DEVICE_TRACKING_REPORT(?,?,?,?,?,?,?,?,?,?,?,?)";

	String FN_GET_STUDY_BASED_REPORT_COUNT = "SELECT FN_GET_STUDY_BASED_REPORT_COUNT(?,?,?,?) as count";
	String GET_STUDY_BASED_REPORT = "CALL GET_STUDY_BASED_REPORT(?,?,?,?,?,?,?,?)";

	String FN_GET_ASSETS_DEVICES_BY_STUDY_REPORT_COUNT = "SELECT FN_GET_ASSETS_DEVICES_BY_STUDY_REPORT_COUNT() as count";
	String ASSET_DASHBOARD_GET_ASSETS_BY_STUDY_STATUS = "ASSET_DASHBOARD_GET_ASSETS_BY_STUDY_STATUS";

	String FN_GET_ASSETS_DEVICES_MALFUNCTIONS_REPORTT = "SELECT FN_GET_ASSETS_DEVICES_MALFUNCTIONS_REPORT() as count";
	String ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE_STUDY = "ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE_STUDY";

	/* pets observation media related procedures & Functions */
	String OBSERVATION_MEDIA_GET_LIST = "CALL OBSERVATION_MEDIA_GET_LIST(?,?,?,?,?,?,?,?,?,?,?)";
	String OBSERVATION_MEDIA_FOR_DUPLICATE_PETS = "CALL OBSERVATION_MEDIA_FOR_DUPLICATE_PETS(?)";
	String FN_GET_OBSERVATION_MEDIA_COUNT = "SELECT FN_GET_OBSERVATION_MEDIA_COUNT(?,?,?,?,?,?,?) as count";
	String OBSERVATION_MEDIA_GET_BY_ID = "CALL OBSERVATION_MEDIA_GET_BY_ID(?)";

	/* devices info bulk insert. */

	String DEVICE_INFO_BULK_INSERT_STAGING = "INSERT INTO `B_DEVICE_DETAILS_STAGING`(`DEVICE_NUMBER`, `DEVICE_TYPE`, `DEVICE_MODEL`, `DEVICE_LOCATION_NAME`, `MFG_SERIAL_NUMBER`, `MFG_FIRMWARE`, `MFG_MAC_ADDR`, `WIFI_MAC_ADDR`, `USER_ID`, `TRACKING_NUMBER`, `STUDY_ID` , `STUDY_NAME`,`WIFI_SSID`, `BOX_NUMBER` ,`FILE_ATTACHMENT_NAME`, `CREATED_DATE`, `EXCEPTION_TYPE`) VALUES"
			+ "	(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),null);";
	String DEVICE_INFO_BULK_VALIDATION_STAGING = "DEVICE_INFO_BULK_VALIDATION_STAGING";
	String DEVICE_INFO_BULK_STAGING_RESULTS_DELETE = "DEVICE_INFO_BULK_STAGING_RESULTS_DELETE";
	String DEVICE_INFO_BULK_SAVE = "DEVICE_INFO_BULK_SAVE";
	String DEVICE_INFO_BULK_STAGING_LIST_COUNT = "SELECT FN_GET_DEVICE_INFO_BULK_UPLOAD_LIST_COUNT(?) as count";
	String DEVICE_INFO_BULK_STAGING_LIST = "CALL DEVICE_INFO_BULK_STAGING_LIST (?,?,?)";

	/* Analytical reports */

	String GET_ANALYTICAL_REPORTS_GROUP = "CALL GET_ANALYTICAL_REPORTS_GROUP()";
	String MANAGE_REPORT_INSERT = "MANAGE_REPORT_INSERT";
	String MANAGE_REPORT_UPDATE = "MANAGE_REPORT_UPDATE";
	String GET_MANAGE_REPORT_GET_BY_ID = "CALL GET_MANAGE_REPORT_GET_BY_ID(?,?)";
	String MANAGE_REPORT_DELETE = "MANAGE_REPORT_DELETE";

	String MANAGE_REPORT_LIST_COUNT = "SELECT FN_GET_MANAGE_REPORT_LIST_COUNT(?,?,?,?) as count";
	String MANAGE_REPORT_GET_LIST = "CALL MANAGE_REPORT_GET_LIST(?,?,?,?,?,?,?,?)";

	String MANAGE_REPORT_GET_LIST_BY_ID_COUNT = "SELECT FN_GET_MANAGE_REPORT_GET_LIST_BY_ID_COUNT(?,?,?) as count";
	String MANAGE_REPORT_GET_LIST_BY_ID = "CALL MANAGE_REPORT_GET_LIST_BY_ID(?,?,?)";

	String PRELUDE_REPORT_GET_LIST_BY_ID_COUNT = "SELECT FN_GET_PRELUDE_REPORT_GET_LIST_BY_ID_COUNT(?,?,?,?,?) as count";
	String PRELUDE_REPORT_GET_LIST_BY_ID = "CALL PRELUDE_REPORT_GET_LIST_BY_ID(?,?,?,?,?,?,?,?,?)";

	/* Timer Log */

	String TIMER_LOG_GET_LIST = "CALL TIMER_LOG_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String TIMER_LOG_GET_LIST_COUNT = " SELECT FN_GET_TIMER_LOG_GET_LIST_COUNT(?,?,?,?,?,?) as count";

	/* Image Scoring Scale related procedures */
	String IMAGE_SCORING_SCALE_INSERT = "IMAGE_SCORING_SCALE_INSERT";
	String IMAGE_SCORING_SCALE_UPDATE = "IMAGE_SCORING_SCALE_UPDATE";
	String IMAGE_SCORING_SCALE_DELETE = "IMAGE_SCORING_SCALE_DELETE";
	String IMAGE_SCORING_SCALE_GET_BY_ID = "IMAGE_SCORING_SCALE_GET_BY_ID";
	String IMAGE_SCORING_SCALE_GET_LIST = "CALL IMAGE_SCORING_SCALE_GET_LIST (?,?,?,?,?,?,?,?)";
	String IMAGE_SCORING_SCALE_GET_ACTIVE_LIST = "CALL IMAGE_SCORING_SCALE_GET_ACTIVE_LIST ()";

	String IMAGE_SCORING_SCALE_LIST_COUNT = "SELECT FN_GET_IMAGE_SCORING_SCALE_LIST_COUNT(?,?,?,?) as count";

	/* Study Push Notifications related procedures */
	String PUSH_NOTIFICATOIN_INSERT = "PUSH_NOTIFICATOIN_INSERT";
	String PUSH_NOTIFICATOIN_UPDATE = "PUSH_NOTIFICATOIN_UPDATE";
	String PUSH_NOTIFICATOIN_DELETE = "PUSH_NOTIFICATOIN_DELETE";
	String PUSH_NOTIFICATOIN_GET_BY_ID = "CALL PUSH_NOTIFICATOIN_GET_BY_ID(?)";
	String PUSH_NOTIFICATOIN_GET_LIST = "CALL PUSH_NOTIFICATOIN_GET_LIST (?,?,?,?,?,?,?,?)";

	String PUSH_NOTIFICATOIN_LIST_COUNT = "SELECT FN_GET_PUSH_NOTIFICATOIN_LIST_COUNT(?,?) as count";

	String STUDY_ASSOCIATE_PUSH_NOTIFICATION = "STUDY_ASSOCIATE_PUSH_NOTIFICATION";
	String STUDY_UPDATE_PUSH_NOTIFICATION = "STUDY_UPDATE_PUSH_NOTIFICATION";
	String STUDY_GET_ASSOCIATED_PUSH_NOTIFICATIONS = "CALL STUDY_GET_ASSOCIATED_PUSH_NOTIFICATIONS(?)";
	String STUDY_DISASSOCIATE_PUSH_NOTIFICATION = "STUDY_DISASSOCIATE_PUSH_NOTIFICATION";
	String STUDY_PUSH_NOTIFICATION_GET_ALL_LIST = "CALL STUDY_PUSH_NOTIFICATION_GET_ALL_LIST()";

	String FN_GET_PUSH_NOTIFICATOIN_LIST_COUNT = "SELECT FN_GET_PUSH_NOTIFICATOIN_LIST_COUNT(?,?,?,?) as count";

	String SHIPMENT_GET_LIST_COUNT = "SELECT FN_GET_SHIPMENT_GET_LIST_COUNT(?,?) as count";
	String SHIPMENT_GET_LIST = "CALL SHIPMENT_GET_LIST(?,?,?,?,?,?)";
	String SHIPMENT_INSERT = "SHIPMENT_INSERT";
	String SHIPMENT_UPDATE = "SHIPMENT_UPDATE";
	String SHIPMENT_STATUS_UPDATE = "SHIPMENT_STATUS_UPDATE";
	String SHIPMENT_GET_BY_ID = "CALL SHIPMENT_GET_BY_ID(?)";
	String SHIPMENT_DELETE = "SHIPMENT_DELETE";

	/* Pet Data Extract module related procedures & Functions */
	String PET_GET_DATA_EXTRACT_LIST_BY_PET_ID = "CALL PET_GET_DATA_EXTRACT_LIST_BY_PET_ID(?)";
	String PET_DATA_EXTRACT_INSERT = "PET_DATA_EXTRACT_INSERT";
	String PET_GET_DETAILS_FOR_DATA_EXTRACT = "CALL PET_GET_DETAILS_FOR_DATA_EXTRACT(?,?,?,?,?,?,?,?,?,?,?,?)";
	String PET_GET_DATA_EXTRACT_CONFIG_LIST = "CALL PET_GET_DATA_EXTRACT_CONFIG_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_PET_GET_DATA_EXTRACT_CONFIG_LIST = "SELECT FN_PET_GET_DATA_EXTRACT_CONFIG_LIST(?,?,?,?,?,?,?,?) as count";
	String FN_PET_GET_DETAILS_FOR_DATA_EXTRACT = "SELECT FN_PET_GET_DETAILS_FOR_DATA_EXTRACT(?,?,?,?,?,?,?,?) as count";
	String PET_GET_DATA_EXTRACT_CONFIG_DETAILS_BY_ID = "CALL PET_GET_DATA_EXTRACT_CONFIG_DETAILS_BY_ID(?)";
	String PET_GET_DETAILS_FOR_DATA_EXTRACT_BY_ID = "PET_GET_DETAILS_FOR_DATA_EXTRACT_BY_ID";

	/* Duplicate Pet module related procedures & functions */
	String PET_GET_PRIMARY_PETS_LIST_COUNT = "SELECT FN_PET_GET_PRIMARY_PETS_LIST_COUNT(?,?,?,?,?,?,?) as count";
	String PET_GET_PRIMARY_PETS_LIST = "CALL PET_GET_PRIMARY_PETS_LIST(?,?,?,?,?,?,?,?,?,?,?)";

	String PET_GET_DATASTREAM_LIST = "CALL PET_GET_DATASTREAM_LIST(?,?)";

	String PET_DUPLICATE_STREAM_INSERT = "PET_DUPLICATE_STREAM_INSERT";

	String PET_GET_DUPLICATE_PETS_CONFIG_COUNT = "SELECT FN_PET_GET_DUPLICATE_PETS_CONFIG_COUNT(?,?,?,?,?,?,?,?) as count";
	String PET_GET_DUPLICATE_PETS_CONFIG_LIST = "CALL PET_GET_DUPLICATE_PETS_CONFIG_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";

	String PET_GET_DUPLICATE_PETS_CONFIG_DETAILS_BY_ID = "CALL PET_GET_DUPLICATE_PETS_CONFIG_DETAILS_BY_ID(?)";

	String PET_GET_PRIMARY_PETS_COUNT = "SELECT FN_PET_GET_PRIMARY_PETS_COUNT(?,?,?,?,?,?,?,?,?) as count";
	String PET_GET_PRIMARY_PETS = "CALL PET_GET_PRIMARY_PETS(?,?,?,?,?,?,?,?,?,?,?,?,?)";

	String PET_GET_DUPLICATE_PETS_COUNT = "SELECT FN_PET_GET_DUPLICATE_PETS_COUNT(?,?,?,?,?,?,?,?,?,?) as count";
	String PET_GET_DUPLICATE_PETS = "CALL PET_GET_DUPLICATE_PETS(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	String PET_DELETE_DUPLICATE_PET = "PET_DELETE_DUPLICATE_PET";

	String GET_POINTS_ACCUMULATED_PETS = "CALL GET_POINTS_ACCUMULATED_PETS(?)";

	String GET_PET_PARENT_REPORT = "CALL GET_QUESTIONNAIRES_BY_PET_PARENT_REPORT(?,?,?,?,?)";

	String FN_GET_PET_BFI_SCORE_REPORT_COUNT = "SELECT FN_GET_PET_BFI_SCORE_REPORT_COUNT(?,?,?,?,?,?)";
	String GET_PET_BFI_SCORE_REPORT = "CALL GET_PET_BFI_SCORE_REPORT(?,?,?,?,?,?,?,?,?,?)";

	String PET_UNASSIGN_ASSET = "PET_UNASSIGN_ASSET";

	String PET_VALIDATE_DUPLICATE_PET = "PET_VALIDATE_DUPLICATE_PET";

	String GET_PET_PARENT_REPORT_COUNT = "SELECT FN_GET_PET_PARENT_REPORT_COUNT(?) as count";

	String ASSET_GET_PET_STUDIES_BY_ASSET = "CALL ASSET_GET_PET_STUDIES_BY_ASSET(?)";
	
	String ASSET_GET_ASSET_BY_SSID = "CALL ASSET_GET_ASSET_BY_SSID(?)";

	String QUESTIONNAIRE_SECTION_LIST = "CALL QUESTIONNAIRE_SECTION_LIST(?)";

	String PET_PARENT_ADDRESSES_BY_PET_ID = "CALL PET_PARENT_ADDRESSES_BY_PET_ID(?)";

	String PET_GET_FORWARD_MOTION_GOAL_SETTING = "CALL PET_GET_FORWARD_MOTION_GOAL_SETTING(?)";

	String PET_PARENT_UPDATE_TIME_ZONE = "PET_PARENT_UPDATE_TIME_ZONE";
	String PET_PARENT_GET_ADDRESS_TIMEZONE = "CALL PET_PARENT_GET_ADDRESS_TIMEZONE()";

	String ASSET_MANAGE_STUDY_MAPPING = "ASSET_MANAGE_STUDY_MAPPING";
	
	String ASSET_GET_ASSET_STATUS = "CALL ASSET_GET_ASSET_STATUS()" ;

	String BIG_QEURY_GET_BEHAVIOR_VISULAZATION = "SELECT PET_ID, TODAY_WALKING, TODAY_RUNNING, LAST_WEEK_FORWARD_MOTION_AVG, PREV_DAY_FORWARD_MOTION, "
			+ "PREV_DAY_TILL_NOW_FM, TODAY_NIGHT_SLEEP, TODAY_DAY_SLEEP, LAST_WEEK_SLEEP_AVG, PREV_DAY_SLEEP, PREV_DAY_TILL_NOW_SLEEP "
			+ "FROM "+HPN_AP_DATASET+".BEHAVIOR_VISUALIZE_VW WHERE PET_ID={0};";

	String BIG_QEURY_GET_BEHAVIOR_HISTORY = "CALL "+HPN_AP_DATASET+".PR_BEHAVIOUR_VISUALIZTION_DAILY_DATA({0},\"{1}\",\"{2}\");";

	/* diet info bulk insert. */

	// String DIET_INFO_BULK_INSERT_STAGING = "CALL
	// DIET_INFO_BULK_INSERT_STAGING(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String DIET_INFO_BULK_INSERT_STAGING = "insert into STG_DIET_UPLOAD_DETAILS("
			+ "  AUDIT_ID, USER_ID, DIET_NUMBER, DIET_NAME, DIET_DESCRIPTION, BRAND, SUB_BRAND, COMPANY_NAME, DIET_DENSITY_KCAL_KG,"
			+ "  CATEGORY, PRODUCT_TYPE, RECIPE_TYPE,  PDM_UOM, PDM_DENSITY_VALUE, LATEST_MODIFIED_DATE, DATASOURCE_ID, CREATED_BY,CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, ERROR_DESCRIPTION"
			+ ")  values (   ?, ?, ?, ?, ?, ?, ?, ?, ?, ?," + "  ?, ?, ?, ?, ? , ?, ?, now(), ?, now(), ?)";
	String DIET_INFO_BULK_INSERT_STAGING_ERROR = "insert into STG_UPLOAD_DIET_ERROR_DETAILS("
			+ " AUDIT_ID, DIET_NUMBER, ERROR_DESCRIPTION, DATASOURCE_ID, CREATED_BY,"
			+ " CREATED_DATE ,MODIFIED_BY, MODIFIED_DATE) values (" + " ?, ?, ?, ?, ?, now(), ?, now()" + " )";
	String CREATE_DIET_UPLOAD_AUDIT = "DIET_UPLOAD_STAGING_AUDIT_LOG_INSERT";
	String UPDATE_DIET_UPLOAD_AUDIT = "DIET_UPLOAD_STAGING_AUDIT_LOG_UPDATE";
	String DIET_INFO_BULK_STAGING_LIST_COUNT = "SELECT FN_GET_DIET_INFO_BULK_UPLOAD_LIST_COUNT(?,?) as count";
	String DIET_INFO_BULK_STAGING_LIST = "CALL DIET_INFO_BULK_STAGING_LIST (?,?,?,?)";
	String DIET_INFO_BULK_SAVE = "DIET_INFO_BULK_SAVE";
	String DIET_INFO_GET_LOOK_UP_DATA = "CALL DIET_INFO_GET_LOOK_UP_DATA()";

	String DIET_INFO_BULK_VALIDATION_STAGING = "DIET_INFO_BULK_VALIDATION_STAGING";
	/*
	String DEVICE_INFO_BULK_STAGING_RESULTS_DELETE = "DEVICE_INFO_BULK_STAGING_RESULTS_DELETE";
	*/
	public final static String DIET_INFO_INSERT = "DIET_INFO_INSERT";
	public final static String DIET_INFO_UPDATE = "DIET_INFO_UPDATE";
	public final static String DIET_INFO_BY_DIET_ID = "CALL DIET_INFO_BY_DIET_ID(?)";
	public final static String DIET_INFO_LIST_COUNT = "SELECT FN_DIET_INFO_LIST_COUNT(?,?,?) AS COUNT";
	public final static String DIET_INFO_LIST = "CALL DIET_INFO_LIST(?,?,?,?,?,?,?)";
	public final static String GET_FOOD_INTAKE_LIST = "CALL GET_FOOD_INTAKE_LIST(?, ?, ?, ?, ?, ?, ?)";
	public final static String GET_FOOD_INTAKE_LIST_COUNT = "SELECT FN_GET_FOOD_INTAKE_LIST(?, ?, ?, ?, ?) as count";

	String PET_UPDATE_MANUAL_RECOMMENDATION = "PET_UPDATE_MANUAL_RECOMMENDATION";

	// String AF_GET_THRESHOLD_BY_ACTION = "CALL AF_GET_THRESHOLD_BY_ACTION(?,?)";
	String AF_GET_THRESHOLD_BY_ACTION = "AF_GET_THRESHOLD_BY_ACTION";

	String GET_FLAGGED_RECOMMENDATION_FILTER = "CALL GET_FLAGGED_RECOMMENDATION_FILTER(?,?,?)";
	String AF_FLAGGED_RECOMMENDATIONS = "CALL AF_FLAGGED_RECOMMENDATIONS(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_GET_AF_FLAGGED_RECOMMENDATIONS_COUNT = "SELECT FN_GET_AF_FLAGGED_RECOMMENDATIONS_COUNT(?,?,?,?,?,?,?,?,?,?,?,?,?) AS COUNT";
	String AF_FLAGGED_RECOMMENDATIONS_UPDATE_STATUS = "AF_FLAGGED_RECOMMENDATIONS_UPDATE_STATUS";

	public final static String FN_GET_STUDY_PHASE_DURATION_BY_STUDY_AND_PHASE = "SELECT FN_GET_STUDY_PHASE_DURATION_BY_STUDY_AND_PHASE(?,?) AS DURATION";

	public final static String STUDY_GET_PHASE_DIETS = "CALL STUDY_GET_PHASE_DIETS(?,?)";

	public final static String STUDY_FEEDING_SCHEDULE_SAVE = "STUDY_FEEDING_SCHEDULE_SAVE";

	public final static String STUDY_PET_CHANGE_TREATMENT_GROUP = "STUDY_PET_CHANGE_TREATMENT_GROUP";

	public final static String STUDY_PET_MOVE_TO_NEXT_PHASE = "STUDY_PET_MOVE_TO_NEXT_PHASE";

	String STUDY_PHASE_GET_FEEDING_RESPONSE_COUNT = "SELECT FN_GET_STUDY_PHASE_FEEDING_RESPONSE_COUNT(?,?,?,?,?) as count";
	String STUDY_PHASE_GET_FEEDING_RESPONSE = "CALL STUDY_PHASE_GET_FEEDING_RESPONSE(?,?,?,?,?,?,?,?,?)";
	String STUDY_GET_FEEDING_SCHEDULE_BY_PET = "CALL STUDY_GET_FEEDING_SCHEDULE_BY_PET(?)";

	String STUDY_PHASE_PUSH_NOTIFICATION_CONFIG = "STUDY_PHASE_PUSH_NOTIFICATION_CONFIG";
	String STUDY_PHASE_GET_PUSH_NOTIFICATION_CONFIG = "CALL STUDY_PHASE_GET_PUSH_NOTIFICATION_CONFIG(?,?)";
	String STUDY_PHASE_IMAGE_SCORING_CONFIG = "STUDY_PHASE_IMAGE_SCORING_CONFIG";
	String STUDY_PHASE_GET_IMAGE_SCORING_CONFIG = "CALL STUDY_PHASE_GET_IMAGE_SCORING_CONFIG(?,?)";
	String STUDY_CREATE_IMAGE_SCORING_SCHEDULE = "STUDY_CREATE_IMAGE_SCORING_SCHEDULE";
	String STUDY_REMOVE_IMAGE_SCORING_SCHEDULE = "STUDY_REMOVE_IMAGE_SCORING_SCHEDULE";
	String STUDY_CREATE_SCHEDULE_PUBLISH_STUDY = "STUDY_CREATE_SCHEDULE_PUBLISH_STUDY";
	String STUDY_COMPLETE_REMOVE_SCHEDULE = "STUDY_COMPLETE_REMOVE_SCHEDULE";
	String STUDY_PHASE_GET_PET_BREEDS = "CALL STUDY_PHASE_GET_PET_BREEDS(?,?)";

	String STUDY_PHASE_QUESTIONNAIRE_CONFIG = "STUDY_PHASE_QUESTIONNAIRE_CONFIG";
	String STUDY_PHASE_DELETE_QUESTIONNAIRE_CONFIG = "STUDY_PHASE_QUESTIONNAIRE_CONFIG_DELETE";
	String STUDY_PHASE_GET_QUESTIONNAIRE_CONFIG = "CALL STUDY_PHASE_GET_QUESTIONNAIRE_CONFIG(?,?)";
	String STUDY_CREATE_QUESTIONNAIRE_SCHEDULE = "STUDY_CREATE_QUESTIONNAIRE_SCHEDULE";
	String STUDY_REMOVE_QUESTIONNAIRE_SCHEDULE = "STUDY_REMOVE_QUESTIONNAIRE_SCHEDULE";

	String STUDY_CREATE_PUSH_NOTIFICATION_SCHEDULE = "STUDY_CREATE_PUSH_NOTIFICATION_SCHEDULE";
	String STUDY_REMOVE_PUSH_NOTIFICATION_SCHEDULE = "STUDY_REMOVE_PUSH_NOTIFICATION_SCHEDULE";

	String STUDY_PHASE_GET_IMAGE_SCORE_RESPONSE_COUNT = "SELECT FN_GET_STUDY_PHASE_IMAGE_SCORE_RESPONSE(?,?,?,?,?,?,?,?) as count";
	String STUDY_PHASE_GET_IMAGE_SCORE_RESPONSE = "CALL STUDY_PHASE_GET_IMAGE_SCORE_RESPONSE(?,?,?,?,?,?,?,?,?,?,?,?)";
	
	String STUDY_PHASE_GET_QUESTIONNAIRE_CONFIG_LIST_COUNT = "SELECT FN_GET_STUDY_PHASE_QUESTIONNAIRE_CONFIG_LIST_COUNT(?,?,?,?,?,?,?,?) as count";
	String STUDY_PHASE_GET_QUESTIONNAIRE_CONFIG_LIST = "CALL STUDY_PHASE_GET_QUESTIONNAIRE_CONFIG_LIST(?,?,?,?,?,?,?,?,?,?,?)";


	String STUDY_PHASE_QUESTIONNAIRE_RESPONSE_LIST_COUNT = "SELECT FN_GET_STUDY_PHASE_QUESTIONNAIRE_RESPONSE_LIST_COUNT(?,?,?,?,?,?,?,?) as count";
	String STUDY_PHASE_QUESTIONNAIRE_RESPONSE_LIST = "CALL STUDY_PHASE_QUESTIONNAIRE_RESPONSE_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";

	String PET_GET_FEEDING_RESPONSE_COUNT = "SELECT FN_GET_PET_FOOD_INTAKE_RESPONSE_COUNT(?,?,?,?,?,?) as count";
	String PET_GET_FOOD_INTAKE_RESPONSE = "CALL PET_GET_FOOD_INTAKE_RESPONSE(?,?,?,?,?,?,?,?,?,?)";
	String STUDY_GET_ALL_PETS = "CALL STUDY_GET_ALL_PETS(?)";

	String GET_PET_THRESHOLD_DETAILS = "CALL GET_PET_THRESHOLD_DETAILS(?)";
	
	/* Device Alerts related procedures & Functions */
	String GET_DEVICE_ALERTS_REPORT = "call GET_DEVICE_ALERTS_REPORT(?,?,?,?,?,?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_ALERTS_REPORT_COUNT = "select FN_GET_DEVICE_ALERTS_REPORT_COUNT(?,?,?,?,?,?,?,?,?) as count";
	String LU_GET_ALERT_TYPE_LIST = "CALL LU_GET_ALERT_TYPES()";
	String LU_GET_ALERT_STYDY_LIST = "CALL LU_GET_ALERT_STUDIES()";
	String GET_DEVICE_ALERTS_DETAILS = "call GET_DEVICE_ALERTS_DETAILS_LIST(?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_ALERTS_DETAILS_COUNT = "select FN_GET_DEVICE_ALERTS_DETAILS_COUNT(?,?,?,?) as count";
	String GET_DEVICE_ALERTS_REPEAT_COUNTS = "call GET_DEVICE_ALERTS_REPEAT_COUNT(?,?,?)";	
	String GET_DEVICE_STUDY_DONUT_GRAPH = "call ALERT_GRAPH_STUDY_DEVCIES(?)";
	String GET_DEVICE_SUMMARY_DONUT_GRAPH = "call ALERT_GRAPH_DEVCIE_SUMMARY(?)";
	String GET_DEVICE_ALERT_COUNT_STACKED = "call ALERT_GRAPH_ALERT_COUNT_STACKED(?)";
	String GET_DEVICE_NON_QUALIFYING_DAYS_GRAPH = "call ALERT_GRAPH_ALERT_NON_QUALIFYING_DAYS(?)";
	String LU_GET_ALERT_DEVICE_LIST = "CALL LU_GET_ALERT_DEVICE_LIST()";
	String LU_GET_ALERT_ACTION_LIST = "CALL LU_GET_ALERT_ACTION_LIST()";
	String LU_GET_ISD_CODES_LIST = "CALL LU_GET_ISD_CODES_LIST()";
	String LU_GET_PET_STUDY_ACTION_LIST = "CALL LU_GET_PET_STUDY_ACTION_LIST()";
	
	String LU_GET_NOTIFICATION_CONFIG = "CALL LU_GET_NOTIFICATION_CONFIG(?)";
	String STUDY_NOTIFICATION_CONFIG_GET_LIST = "CALL STUDY_NOTIFICATION_CONFIG_GET_LIST(?)";
	String STUDY_NOTIFICATION_CONFIG_INSERT = "STUDY_NOTIFICATION_CONFIG_INSERT";
	String PET_NOTIFICATION_INSERT = "PET_NOTIFICATION_INSERT";
	
	String QUESTIONNAIRE_EXPORT_REQUEST_LIST = "call QUESTIONNAIRE_EXPORT_REQUEST_LIST(?,?,?,?,?,?)";
	String QUESTIONNAIRE_EXPORT_INSERT = "QUESTIONNAIRE_EXPORT_INSERT";
	String QUESTIONNAIRE_EXPORT_GET_QUESTIONNAIRES="call QUESTIONNAIRE_EXPORT_GET_QUESTIONNAIRES(?)";
	String QUESTIONNAIRE_EXPORT_UPDATE = "QUESTIONNAIRE_EXPORT_UPDATE";
	String QUESTIONNAIRE_EXPORT_REQUEST_LIST_COUNT = "SELECT FN_GET_QUESTIONNAIRE_EXPORT_REQUEST_LIST_COUNT(?) as count";
	String QUESTIONNAIRE_EXPORT_DOWNLOAD ="call QUESTIONNAIRE_EXPORT_DOWNLOAD(?)";
	String QUESTIONNAIRE_GET_LIST_FOR_EXPORT_COUNT = "SELECT FN_GET_QUESTIONNAIRE_FOR_EXPORT_COUNT(?,?,?,?,?,?) as count";
	String ASSET_BULK_WHITELISTING = "ASSET_BULK_WHITELISTING";
}
